export const COLORS = {
    DARK_BG: '#141414',
    INPUT_BG: '#242424',
    CARD_BG: '#1E1E1E',
    BORDER: '#2A2A2A',
    BTN_BLUE: '#4A7FA5',
    ACCENT_BLUE: '#5B9EC9',
    WHITE: '#FFFFFF',
    GRAY: '#888888',
    LABEL: '#FFFFFF',
    ERROR: '#E53935',
    SUCCESS: '#00C896',
    WARNING: '#FFA040',
    MUTED: '#555',
    BLUE_MIST: '#1A3D5A',
    DARK_MIST: '#1A3D2E',
    MID_GRAY: '#3A3A3A',
    ICON_BOX: '#3A6B8A',
    BLACK: '#000000',
    VALID_GREEN: '#6BCB77',
    INVALID_RED: '#FF6B6B',
    RESULT_DARK: '#1A1A1A',
    RESULT_GRAY: '#4A4A4A',
    HIGHLIGHT_GREEN: '#2A6B4A',
    LIGHT_GREEN: '#5BC99A',
    DARK_GRAY: '#1C1C1C',
    DOT_GRAY: '#444',
    TEXT_MUTED: '#666',
    TRANSPARENT: 'transparent',
};

export const Colors = {
    light: {
        text: '#000000',
        background: '#FFFFFF',
        tint: COLORS.BTN_BLUE,
        icon: COLORS.BTN_BLUE,
        tabIconDefault: COLORS.GRAY,
        tabIconSelected: COLORS.BTN_BLUE,
        inputBackground: '#F0F0F0',
        error: COLORS.ERROR,
    },
    dark: {
        text: COLORS.LABEL,
        background: COLORS.DARK_BG,
        tint: COLORS.BTN_BLUE,
        icon: COLORS.ACCENT_BLUE,
        tabIconDefault: COLORS.GRAY,
        tabIconSelected: COLORS.ACCENT_BLUE,
        inputBackground: COLORS.INPUT_BG,
        error: COLORS.ERROR,
        iconBox: COLORS.ICON_BOX,
    },
};
